name: build, test, and publish a .net nuget package

on:
  push:
    branches: [ main ]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_BUILD_VERSION: '0.0.0-${{ github.ref_name }}-${{github.run_number}}'
      TAG_BUILD_VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x
      - name: pack Nathanael.DI
        run: dotnet pack ./src/Nathanael.DI/Nathanael.DI.csproj -o ./nugets -p:Version=${{ github.ref_type == 'tag' && env.TAG_BUILD_VERSION || env.BRANCH_BUILD_VERSION }}
      - name: pack Nathanael.DI.Hosting
        run: dotnet pack ./src/Nathanael.DI.Hosting/Nathanael.DI.Hosting.csproj -o ./nugets -p:Version=${{ github.ref_type == 'tag' && env.TAG_BUILD_VERSION || env.BRANCH_BUILD_VERSION }}
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            src
            nugets
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x
      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Run tests with dotnet CLI
        run: dotnet test ./src/Nathanael.DI.Tests/Nathanael.DI.Tests.csproj

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x
      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      # - name: mock publishing nugets
      #   run: |
      #        for file in ./nugets/*.nupkg; do
      #           dotnet nuget push $file -k ${{ secrets.NUGET_ORG_API_KEY }} -s staging.nuget.org
      #        done
      - name: print envs
        run: env
