name: build, test, and publish a .net nuget package

on:
  push:
    branches: [ main ]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: ${{github.event_path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x
      - name: hello world
        run: |
             dotnet --list-sdks
             pwd
             dir 
             env
      - name: pack Nathanael.DI
        run: dotnet pack ./Nathanael.DI/Nathanael.DI.csproj -o ./nugets 
      - name: pack Nathanael.DI.Hosting
        run: dotnet pack ./Nathanael.DI.Hosting/Nathanael.DI.Hosting.csproj -o ./nugets 
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: print envs
        run: env

  publish:
    needs: test
    runs-on: ubuntu-latest
    

    steps:
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
