name: build, test, and publish a .net nuget package

on:
  push:
    branches: [ main ]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: ${{ github.ref_type == 'tag' && '' || '0.0.0-' }}${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x
      - name: hello world
        run: |
             dotnet --list-sdks
             pwd
             dir 
             env
      - name: pack Nathanael.DI
        run: dotnet pack ./Nathanael.DI/Nathanael.DI.csproj -o ./nugets -p:Version=${{ env.BUILD_VERSION }}
      - name: pack Nathanael.DI.Hosting
        run: dotnet pack ./Nathanael.DI.Hosting/Nathanael.DI.Hosting.csproj -o ./nugets -p:Version=${{ env.BUILD_VERSION }}
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x
      - name: Run tests with dotnet CLI
        run: dotnet test ./Nathanael.DI.Tests/Nathanael.DI.Tests.csproj

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
