name: build, test, and publish a .net nuget package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x
      - name: hello world
        run: |
             dotnet --list-sdks
             pwd
             dir 
      - name: pack
        run: donet pack -o ./nugets 