name: build, test, and publish a .net nuget package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x
      - name: hello world
        run: |
             dotnet --list-sdks
             pwd
             dir 
      - name: pack Nathanael.DI
        run: dotnet pack ./Nathanael.DI/Nathanael.DI.csproj -o ./nugets 
      - name: pack Nathanael.DI.Hosting
        run: dotnet pack ./Nathanael.DI.Hosting/Nathanael.DI.Hosting.csproj -o ./nugets 